# Generated by Django 5.1.1 on 2025-10-23 08:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_workspace_plan'),
        ('billing', '0002_alter_plan_workspace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='start_date',
        ),
        migrations.AddField(
            model_name='plan',
            name='end_at',
            field=models.DateTimeField(blank=True, help_text='Required if term is LIMITED.', null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='start_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the plan starts being active.'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='active',
            field=models.BooleanField(default=True, help_text='Set inactive to pause this plan immediately.'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='bundle',
            field=models.CharField(choices=[('FULL', 'Full (AI + Live + Q&A)'), ('LIVE_QA', 'Live + Q&A'), ('AI_ONLY', 'AI Only'), ('LIVE_ONLY', 'Live Only'), ('QA_ONLY', 'Q&A Only')], default='AI_ONLY', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='term',
            field=models.CharField(choices=[('LIFETIME', 'Lifetime'), ('LIMITED', 'Limited Time Window')], default='LIFETIME', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('workspace',), name='unique_active_plan_per_workspace'),
        ),
    ]
