# Generated by Django 5.1.1 on 2025-10-18 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Redbot', max_length=255)),
                ('public_key', models.CharField(max_length=255, unique=True)),
                ('preferred_mode', models.CharField(default='AI', max_length=10)),
                ('ai_provider', models.CharField(default='openai', max_length=50)),
                ('ai_model', models.CharField(default='gpt-4o-mini', max_length=50)),
                ('_ai_api_key', models.BinaryField(blank=True, null=True)),
                ('allowed_domains', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.workspace')),
            ],
        ),
    ]
