# Generated by Django 5.1.1 on 2025-10-18 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='_ai_api_key',
        ),
    ]
