# Generated by Django 5.1.1 on 2025-10-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_remove_bot__ai_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='_ai_api_key',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
