# Generated by Django 5.1.1 on 2025-10-18 06:01

import bots.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_bot__ai_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='ai_model',
            field=models.CharField(default='gemini-2.0-flash-exp', max_length=50),
        ),
        migrations.AlterField(
            model_name='bot',
            name='ai_provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('google', 'Google AI')], default='google', max_length=50),
        ),
        migrations.AlterField(
            model_name='bot',
            name='public_key',
            field=models.CharField(default=bots.models.generate_public_key, max_length=255, unique=True),
        ),
    ]
