# Generated by Django 5.1.1 on 2025-10-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_alter_bot_ai_model_alter_bot_ai_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='ai_provider',
            field=models.CharField(default='google', max_length=50),
        ),
    ]
