# Generated by Django 5.1.1 on 2025-10-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0005_alter_bot_ai_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='ai_model',
            field=models.CharField(default='gpt-4o', max_length=50),
        ),
        migrations.AlterField(
            model_name='bot',
            name='ai_provider',
            field=models.CharField(choices=[('google', 'Google'), ('openai', 'OpenAI'), ('openrouter', 'OpenRouter'), ('anthropic', 'Anthropic'), ('xai', 'xAI'), ('cohere', 'Cohere'), ('huggingface', 'Hugging Face'), ('deepseek', 'DeepSeek'), ('meta', 'Meta AI'), ('mistral', 'Mistral AI'), ('groq', 'Groq'), ('togetherai', 'Together AI'), ('perplexity', 'Perplexity AI'), ('replicate', 'Replicate'), ('alezeia', 'Alezeia')], default='openrouter', max_length=50),
        ),
    ]
