# Generated by Django 5.1.1 on 2025-10-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0006_alter_bot_ai_model_alter_bot_ai_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='ai_model',
            field=models.CharField(default='gpt-4o', max_length=255),
        ),
    ]
