# Generated by Django 5.1.1 on 2025-10-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0007_alter_bot_ai_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='ai_model',
            field=models.CharField(blank=True, default='gpt-4o', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='ai_provider',
            field=models.CharField(blank=True, choices=[('google', 'Google'), ('openai', 'OpenAI'), ('openrouter', 'OpenRouter'), ('anthropic', 'Anthropic'), ('xai', 'xAI'), ('cohere', 'Cohere'), ('huggingface', 'Hugging Face'), ('deepseek', 'DeepSeek'), ('meta', 'Meta AI'), ('mistral', 'Mistral AI'), ('groq', 'Groq'), ('togetherai', 'Together AI'), ('perplexity', 'Perplexity AI'), ('replicate', 'Replicate'), ('alezeia', 'Alezeia')], default='openrouter', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bot',
            name='allowed_domains',
            field=models.TextField(blank=True, help_text='One domain per line or comma-separated. Examples: example.com, app.example.com'),
        ),
    ]
