# Generated by Django 5.2.7 on 2025-11-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0008_alter_bot_ai_model_alter_bot_ai_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='ui_font_family',
            field=models.CharField(default='Inter, system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif', max_length=200),
        ),
        migrations.AddField(
            model_name='bot',
            name='ui_font_size',
            field=models.PositiveSmallIntegerField(default=14),
        ),
        migrations.AddField(
            model_name='bot',
            name='ui_primary_color',
            field=models.CharField(default='#2563eb', max_length=7),
        ),
        migrations.AddField(
            model_name='bot',
            name='ui_sound_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bot',
            name='ui_welcome_message',
            field=models.CharField(default="Hi! I'm {name}. How can I help you?", max_length=255),
        ),
        migrations.AlterField(
            model_name='bot',
            name='allowed_domains',
            field=models.TextField(blank=True, help_text='One hostname per line, e.g., localhost, 127.0.0.1'),
        ),
    ]
