# Generated by Django 5.2.7 on 2025-11-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0009_bot_ui_font_family_bot_ui_font_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='ui_animation_speed',
            field=models.CharField(choices=[('normal', 'Normal'), ('fast', 'Fast'), ('slow', 'Slow'), ('none', 'None (Accessibility)')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='bot',
            name='ui_bg_color',
            field=models.CharField(default='#f9fafb', help_text='Chat background color (hex)', max_length=7),
        ),
        migrations.AddField(
            model_name='bot',
            name='ui_widget_position',
            field=models.CharField(choices=[('bottom-right', 'Bottom Right'), ('bottom-left', 'Bottom Left')], default='bottom-right', max_length=15),
        ),
    ]
