# Generated by Django 5.2.7 on 2025-11-12 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_workspace_bot_footer'),
        ('bots', '0010_bot_ui_animation_speed_bot_ui_bg_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(default='Redback', max_length=255)),
                ('c_url', models.URLField(default='https://redback.in/')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_footers', to='accounts.workspace')),
            ],
            options={
                'verbose_name': 'Bot Footer',
                'verbose_name_plural': 'Bot Footers',
            },
        ),
    ]
