# Generated by Django 5.2.7 on 2025-11-14 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_workspace_enable_enquiry_form'),
        ('bots', '0011_botfooter'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_enquiries', to='accounts.workspace')),
            ],
            options={
                'verbose_name': 'Bot Enquiry',
                'verbose_name_plural': 'Bot Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
