# Generated by Django 5.2.7 on 2025-10-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_knowledgesource_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgesource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
