# Generated by Django 5.2.7 on 2025-12-01 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0012_botenquiry'),
        ('knowledge', '0003_knowledgesource_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='QAPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='The main question or category.', max_length=255)),
                ('answer', models.TextField(blank=True, help_text='The answer (if leaf node) or description.', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering index')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_pairs', to='bots.bot')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='knowledge.qapair')),
            ],
            options={
                'verbose_name': 'Q&A Pair',
                'verbose_name_plural': 'Q&A Pairs',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
