# Generated by Django 5.0.7 on 2026-02-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='message',
            name='completion_tokens',
            field=models.IntegerField(blank=True, help_text='Output tokens generated', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='prompt_tokens',
            field=models.IntegerField(blank=True, help_text='Input tokens used', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='total_tokens',
            field=models.IntegerField(blank=True, help_text='Total tokens (prompt + completion)', null=True),
        ),
    ]
