# Generated by Django 5.1.1 on 2025-10-18 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_workspace_created_at'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspaces', to='billing.plan'),
        ),
    ]
