# Generated by Django 5.1.1 on 2025-10-23 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_workspace_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='plan',
        ),
    ]
