# Generated by Django 5.2.7 on 2025-11-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_workspace_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='bot_footer',
            field=models.BooleanField(default=False),
        ),
    ]
