# Generated by Django 5.2.7 on 2025-11-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_workspace_bot_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='enable_enquiry_form',
            field=models.BooleanField(default=False, help_text='Show name/phone/email form to chat visitors'),
        ),
    ]
