# Generated by Django 5.2.7 on 2025-11-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_workspace_enable_enquiry_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='enable_reset_button',
            field=models.BooleanField(default=True, help_text='Show the Reset button in the chat widget'),
        ),
    ]
