# Generated by Django 5.2.7 on 2025-12-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_workspace_enable_reset_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='default_bot_mode',
            field=models.CharField(blank=True, choices=[('AI', 'AI Bot'), ('LIVE', 'Live Chat'), ('QA', 'Q&A Bot')], help_text='Default bot to show for multi-bot plans (FULL/LIVE_QA)', max_length=10, null=True),
        ),
    ]
