# Generated by Django 5.2.7 on 2025-12-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_workspace_default_bot_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='contact_address',
            field=models.TextField(blank=True, help_text='Address to show when AI cannot answer', null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Email to show when AI cannot answer', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Phone number to show when AI cannot answer', max_length=20, null=True),
        ),
    ]
