# Generated by Django 5.2.7 on 2025-12-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_workspace_contact_address_workspace_contact_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='contact_address',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='contact_phone',
        ),
        migrations.AddField(
            model_name='workspace',
            name='enable_whatsapp_number_in_chat',
            field=models.BooleanField(default=False, help_text="Show WhatsApp contact link in AI 'no relevant info' responses"),
        ),
        migrations.AddField(
            model_name='workspace',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp number for customer support (include country code, e.g., +919876543210)', max_length=20, null=True),
        ),
    ]
