# Generated by Django 5.2.7 on 2025-12-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_workspace_contact_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='enable_website_datafetcher',
            field=models.BooleanField(default=False, help_text='Enable website data fetcher in dashboard'),
        ),
    ]
