# Generated by Django 5.2.7 on 2025-12-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_workspace_enable_website_datafetcher'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='qdrant_api_key',
            field=models.CharField(blank=True, help_text='Default Qdrant API Key for new chunks', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='qdrant_url',
            field=models.URLField(blank=True, help_text='Default Qdrant URL for new chunks', null=True),
        ),
    ]
