# Generated by Django 5.2.7 on 2026-01-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_workspace_qdrant_api_key_workspace_qdrant_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='enable_bot_widget',
            field=models.BooleanField(default=True, help_text='Master toggle to enable/disable the bot widget'),
        ),
    ]
