# Generated by Django 5.2.7 on 2026-01-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_workspace_enable_bot_widget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gmail', models.EmailField(max_length=254)),
                ('whatsappnumber', models.CharField(max_length=20)),
                ('business_name', models.CharField(max_length=255)),
                ('plane', models.CharField(choices=[('Full Pack', 'Full Pack'), ('Live & FAQ', 'Live & FAQ'), ('AI', 'AI'), ('Livechat', 'Livechat'), ('FAQ', 'FAQ')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
